"""initial

Revision ID: 2c41a82f6549
Revises: 
Create Date: 2026-08-27 21:43:14.780518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from app.services.seed_service import seed_default_folders, seed_default_owner

# revision identifiers, used by Alembic.
revision: str = '2c41a82f6549'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channels_owner_id'), ['owner_id'], unique=False)

    op.create_table('contact_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('category_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_folders', schema=None) as batch_op:
        batch_op.create_index('idx_folders_owner_category_key', ['owner_id', 'category_key'], unique=True, sqlite_where=sa.text('category_key IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_contact_folders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_folders_owner_id'), ['owner_id'], unique=False)

    op.create_table('contact_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_tags_owner_id'), ['owner_id'], unique=False)

    op.create_table('import_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_pattern', sa.String(length=255), nullable=True),
    sa.Column('mapping', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_mappings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_mappings_owner_id'), ['owner_id'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sqlite.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_settings_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('uq_settings_owner_key', ['owner_id', 'key'], unique=True)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=100), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('chat_type', sa.String(length=20), nullable=True),
    sa.Column('is_known', sa.Boolean(), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('contact_type', sa.String(length=20), server_default='other', nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('auto_reply_enabled', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['contact_folders.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_chat_type'), ['chat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_is_important'), ['is_important'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_is_known'), ['is_known'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_is_spam'), ['is_spam'], unique=False)
        batch_op.create_index('ix_contacts_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('uq_contacts_owner_telegram', ['owner_id', 'telegram_id'], unique=True, sqlite_where=sa.text('telegram_id IS NOT NULL'))

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('recurrence', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_id'), ['id'], unique=False)
        batch_op.create_index('ix_calendar_events_owner_date', ['owner_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_owner_id'), ['owner_id'], unique=False)

    op.create_table('contact_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_fields_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_fields_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_fields_owner_id'), ['owner_id'], unique=False)

    op.create_table('contact_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_notes_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_notes_owner_id'), ['owner_id'], unique=False)

    op.create_table('contact_tag_association',
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['contact_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('channel_message_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_pinned'), ['is_pinned'], unique=False)
        batch_op.create_index('ix_messages_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_snoozed_until'), ['snoozed_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_status'), ['status'], unique=False)
        batch_op.create_index('uq_owner_channel_message', ['owner_id', 'channel', 'channel_message_id'], unique=True, sqlite_where=sa.text('deleted_at IS NULL'))

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
      sa.Column('due_date', sa.DateTime(), nullable=True),
      sa.Column('reminder_minutes', sa.Integer(), nullable=True),
      sa.Column('recurrence', sa.String(length=500), nullable=True),
      sa.Column('last_reminded_at', sa.DateTime(), nullable=True),
      sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
      sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
      sa.Column('deleted_at', sa.DateTime(), nullable=True),
      sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index('ix_tasks_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_message_id', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attachments_channel_message_id'), ['channel_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attachments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('outbox_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_messages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_outbox_status_next_retry', ['status', 'next_retry_at'], unique=False)

    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_comments_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###

    conn = op.get_bind()
    seed_default_owner(conn)
    seed_default_folders(conn)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_owner_id'))
        batch_op.drop_index(batch_op.f('ix_task_comments_id'))

    op.drop_table('task_comments')
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_status_next_retry')
        batch_op.drop_index(batch_op.f('ix_outbox_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_owner_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_message_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_id'))
        batch_op.drop_index(batch_op.f('ix_outbox_messages_channel'))

    op.drop_table('outbox_messages')
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attachments_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_attachments_id'))
        batch_op.drop_index(batch_op.f('ix_message_attachments_channel_message_id'))

    op.drop_table('message_attachments')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_owner_id'))
        batch_op.drop_index('ix_tasks_owner_created')
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_tasks_contact_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('uq_owner_channel_message', sqlite_where=sa.text('deleted_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_messages_status'))
        batch_op.drop_index(batch_op.f('ix_messages_snoozed_until'))
        batch_op.drop_index(batch_op.f('ix_messages_owner_id'))
        batch_op.drop_index('ix_messages_owner_created')
        batch_op.drop_index(batch_op.f('ix_messages_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_messages_is_flagged'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_messages_contact_id'))
        batch_op.drop_index(batch_op.f('ix_messages_channel'))

    op.drop_table('messages')
    op.drop_table('contact_tag_association')
    with op.batch_alter_table('contact_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_notes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contact_notes_id'))
        batch_op.drop_index(batch_op.f('ix_contact_notes_contact_id'))

    op.drop_table('contact_notes')
    with op.batch_alter_table('contact_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_fields_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contact_fields_id'))
        batch_op.drop_index(batch_op.f('ix_contact_fields_contact_id'))

    op.drop_table('contact_fields')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_owner_id'))
        batch_op.drop_index('ix_calendar_events_owner_date')
        batch_op.drop_index(batch_op.f('ix_calendar_events_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_date'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_contact_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('uq_contacts_owner_telegram', sqlite_where=sa.text('telegram_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_contacts_owner_id'))
        batch_op.drop_index('ix_contacts_owner_created')
        batch_op.drop_index(batch_op.f('ix_contacts_is_spam'))
        batch_op.drop_index(batch_op.f('ix_contacts_is_known'))
        batch_op.drop_index(batch_op.f('ix_contacts_is_important'))
        batch_op.drop_index(batch_op.f('ix_contacts_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_folder_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_contacts_contact_type'))
        batch_op.drop_index(batch_op.f('ix_contacts_chat_type'))

    op.drop_table('contacts')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index('uq_settings_owner_key')
        batch_op.drop_index(batch_op.f('ix_settings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_settings_key'))
        batch_op.drop_index(batch_op.f('ix_settings_id'))

    op.drop_table('settings')
    with op.batch_alter_table('import_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_mappings_owner_id'))
        batch_op.drop_index(batch_op.f('ix_import_mappings_id'))

    op.drop_table('import_mappings')
    with op.batch_alter_table('contact_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_tags_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contact_tags_id'))

    op.drop_table('contact_tags')
    with op.batch_alter_table('contact_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_folders_owner_id'))
        batch_op.drop_index(batch_op.f('ix_contact_folders_id'))
        batch_op.drop_index('idx_folders_owner_category_key', sqlite_where=sa.text('category_key IS NOT NULL'))

    op.drop_table('contact_folders')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_owner_id'))
        batch_op.drop_index(batch_op.f('ix_channels_id'))

    op.drop_table('channels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
